services:
  - type: web
    name: deutsch-check-bot
    env: python
    buildCommand: |
      poetry install
      poetry run playwright install --with-deps
    startCommand: poetry run python telegram_bot.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: PYTHONUNBUFFERED
        value: "1"

